== Deployment

Deployment of the {project-short-name} consists of deploying all necessary
dependencies and then the module itself into OpenMRS.

You need to login to your OpenMRS instance as administrative user and go to the
Administration, Manage Modules page and add the modules shown in the following
sections.

=== Module Dependencies

The {project-short-name} currently depends on the

1. OpenMRS Webservices REST module - version {openmrs-dependency-rest-version}
2. OpenMRS Legacy UI module - version {openmrs-dependency-legacyui-version}

You can get the Legacy UI at {openmrs-modulus-url}[OpenMRS modules].
The Webservices REST with the feature needed for the {project-short-name} have not
been released yet, you either have to compile it yourself or just until a
release has been made you can get it at {project-tmp-dependency-repo}.

=== Module Package

Since there has not been an official release yet you need to compile the
{project-short-name} yourself.

Please follow the instructions at {project-source-code}.

