== Requirements

:ihe-tf-rad-title: IHE Radiology Technical Framework
:ihe-tf-rad-vol2: IHE Radiology Technical Framework Vol 2
:ihe-tf-rad-url: http://www.ihe.net/Technical_Frameworks/#radiology

This documents shall serve as a requirement for ongoing development and a
documentation of how things are implemented by the {project-short-name}.

The {project-short-name} aims to adhere to best practices defined by the
{ihe-tf-rad-url}[{ihe-tf-rad-title}].

The {project-short-name} shall partially implement the following integration profiles:

* Radiology Scheduled Workflow (SWF)

NOTE: the word partially is used above since {project-short-name} will not
perform all transactions required by the {ihe-tf-rad-title}.

The {project-short-name} acts as the following actors:

* Order Placer (OP)
* Department System Scheduler/Order Filler (DSS/OF)

NOTE: the module does not provide DICOM Modality Worklist services as
attributed to actor 'Department System Scheduler/Order Filler' by IHE, this
service has to be provided by an external system (like a PACS, as for example
done by dcm4chee).

The {project-short-name} implements or acts in the following transactions:

* RAD-2 Placer Order Management
* RAD-3 Filler Order Management
* RAD-4 Procedure Scheduled
* RAD-13 Procedure Update

NOTE: since the {project-short-name} acts as 'Order Placer' and 'Department
System Scheduler/Order Filler' transaction 'RAD-2' and 'RAD-3' are basically merged.
There is no need for the 'DSS/OF' to update/notify the 'OP' on creation, revision,
cancellation of orders, since these actions will always originate at the 'OP'.

=== Background

The following explains the meaning of terms used in this document

* requested procedure: a unit of work which results in a report
* scheduled procedure: smallest unit of work which is scheduled and performed
* performed procedure: smallest unit of work that has actually been performed
which will result in images

=== User Roles

The following describes the user roles interacting with the {project-short-name}.

==== Administrator - AD

Administrator of the {project-short-name} configures orderables, DICOM UID org
root used for DICOM Study Instance UID generation, DICOM web viewer details and
other OpenMRS related settings.

==== Referring Physician - RP

Doctor ordering a radiological test to be done on a patient.

==== Scheduler - SC

Provider who schedules (sets date, time and location/modality) requested imaging procedures.

==== Performing Technician - PT

Technologist performing the imaging procedures on the
patient. To get the scheduled procedures (his TODO list) he has to perform he
can either find it in the {project-short-name} or at the modality through querying
the DICOM Modality Worklist from the PACS.

==== Radiologist - RA

Radiologist creates radiological reports for completed requested
procedures.

=== User stories

==== Referring Physician - RP

===== RP-1 CREATE ORDER

STORY:: As a referring physician I want to create a new radiology order.

ACCEPTANCE CRITERIA::

* select patient
* select orderable from concept (i.e. "R/O pulmonary embolism")
* select urgency
* select date and time if order should be scheduled for specific date
* select orderer from providers (in case I am not an RP, but a data clerk with
RP permissions entering the order for an RP)
* enter order reason as free text or from concept (Order.orderReasonNonCoded/orderReason)
* enter a comment for the fulfiller of the order (Order.commentToFulfiller)

NOTE: creating a radiology order does not create a requested procedure, this
transaction represents the 'Order Placer' sending an order request to the
'Department System Scheduler/Order Filler' in terms of IHE actors. In other
terms, any department allowed to create radiology orders sends a request for a
radiology order to the radiology department, but does not interfere with the
exact details of how the order is going to be executed/reported/billed. These
details are a matter of the radiology department.

===== RP-2 DISCONTINUE ORDER

STORY:: As a referring physician I want to discontinue an existing radiology order.

ACCEPTANCE CRITERIA::

* a radiology order can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A radiology order can be discontinued even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued.

===== RP-3 REVISE ORDER

STORY:: As a referring physician I want to revise an existing radiology order.

ACCEPTANCE CRITERIA::

* a radiology order can only be revised as long as no imaging procedure
has been performed.

NOTE: A radiology order can be revised even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued since they might no longer match the orderable.
The radiology department will need to create a new requested procedure with its
scheduled procedures for the revised order as if it was a new order.

===== RP-4 LIST ORDERS

STORY:: As a referring physician I want to see a list of radiology orders where
I can narrow down the results by filtering and navigate to a specific radiology
order's or its requested procedure page.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** order date
** filter/see if the order has been requested by the radiology department
(does it have a requested procedure?)
* I can navigate to the radiology order form by selecting a hyperlink in a specific
radiology order's row (for revision/discontinuation of the order)
* I can navigate to the radiology order's requested procedure (if existing) by
selecting a hyperlink in a specific radiology order's row (to see details about
the requested procedure: scheduled procedures, performed procedures, radiology
report, study)

==== Scheduler - SC

===== SC-1 LIST SCHEDULED PROCEDURES

STORY:: As a scheduler I want to see a list of scheduled procedures where
I can narrow down the results by filtering and navigate to a specific scheduled
procedure's page.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
** scheduled procedure id
** corresponding requested procedure id
** scheduled procedure start datetime
** scheduled procedure's imaging procedure
** scheduled procedure's modality type
** corresponding performed procedure id
* I can filter the list by
** patient name or id
** scheduled procedure start datetime
** scheduled procedure's imaging procedure
** scheduled procedure's modality type
** scheduled status; already scheduled or not
** performed status; already performed or not
* I can navigate to a scheduled procedure's form by selecting the
hyperlink on the scheduled procedure's id.
* I can navigate to a corresponding requested procedure's form by selecting the
hyperlink on the corresponding requested procedure id.
* I can navigate to a corresponding performed procedure's form by selecting the
hyperlink on the corresponding performed procedure id.

===== SC-2 SCHEDULE PROCEDURES

STORY:: As a scheduler I want to define when (date and time) scheduled procedures will be performed.

ACCEPTANCE CRITERIA::

On a scheduled procedures page

* If the requested procedure of the scheduled procedure I am working on has a
radiology order, a header summarizing the radiology order information should
show. The radiology order header shows
** patient
** order number
** accession number
** orderable
** orderer
** urgency
** date and time
* I can see a header with the requested procedure information of the scheduled
procedures requested procedure. The requested procedure header shows
** requested procedure id
** requested procedure
* I can set the scheduled procedure's start datetime and save it

===== SC-3 DISCONTINUE SCHEDULED PROCEDURE

STORY:: As a scheduler I want to discontinue an existing scheduled
procedure.

ACCEPTANCE CRITERIA::

On a scheduled procedures page
* I can enter
** discontinuation reason (i.e. equipment maintenance, patient did not arrive)
** provider who ordered the discontinuation
* a scheduled procedure can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A requested procedure can be discontinued even if it already has scheduled
procedures, but only as long as there is no performed procedure. The existing requested
procedure and its scheduled procedures will be discontinued.

==== Performing Technician - PT

===== PT-1 CREATE REQUESTED PROCEDURE

STORY:: As a performing technician I want to create a requested procedure for a
radiology order.

ACCEPTANCE CRITERIA::

* see a header with the radiology order information of the order I am creating
a requested procedure for (accession number, orderable, orderer, urgency, date
and time, patient)
* select requested procedure from concept (i.e. X-RAY, CHEST)
* QUESTION select a provider which requests this requested procedure (in case I am not a
PT, but a data clerk with PT permissions entering the requested procedure for a PT)
* when I save the requested procedure a study is also created with a Study
Instance UID

IMPORTANT: this story needs clarification. I chose this step to be done by the PT but
it could of course be done by someone else. The step could be automated in case
we have a mechanism in place that maps all orderables to requested procedures
as described by {ihe-tf-rad-title} in 3.4.2 Scheduled Workflow Concepts in
Practice see example of "R/O Pulmonary Embolism". The mapping would then be
configured by each implemenation.

NOTE: the use of the requested procedure is to be able refine how the orderable
is mapped to an imaging procedure. a different kind of code could be used for
orderables and requested procedures. the orderable is closer to what should be
done in an abstract sense and the requested procedure closer to the imaging
procedure.

===== PT-2 DISCONTINUE REQUESTED PROCEDURE

STORY:: As a performing technician I want to discontinue an existing requested
procedure.

ACCEPTANCE CRITERIA::

* a requested procedure can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A requested procedure can be discontinued even if it already has scheduled
procedures, but only as long as there is no performed procedure. The existing requested
procedure and its scheduled procedures will be discontinued.

===== PT-3 ADD SCHEDULED PROCEDURES

STORY:: As a performing technician I want to create and add scheduled procedures to a
requested procedure.

ACCEPTANCE CRITERIA::

* I can see a header with the requested procedure I am adding scheduled
procedures to. The header shows
** radiology order (if exists)
** requested procedure concept
* I can see existing scheduled procedures
* I can add a new scheduled procedure
** select an imaging procedure from concepts 
** select a modality type (CT, MR, US, ... see DICOM standard part 3
C.7.3.1.1.1)

NOTE: again this step could be done by another role, or if a mechanism for
mapping requested procedures to scheduled procedures exists it could be
automated or at least pre-filled for the PT which accepts it (but that would be
another story)

===== PT-4 LIST REQUESTED PROCEDURES

STORY:: As a performing technician I want to see a list of requested procedures
where I can narrow down the results by filtering and navigate to a specific
requested procedure's page.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** requested procedure code
** status; not yet performed; performed (has performed procedures?)
* I can navigate to the requested procedure's page by
selecting a hyperlink in a specific requested procedure's row

===== PT-5 MARK SCHEDULED PROCEDURE AS COMPLETE

STORY:: As a performing technician I want to mark a scheduled procedure as
completed.

ACCEPTANCE CRITERIA::

* when I select the scheduled procedure to complete it I am redirected to the
performed procedure form with all info from the scheduled procedure pre-filled
in the performed procedure's fields
** scheduled procedure start datetime as performed procedure start datetime
** scheduled procedure imaging procedure as performed procedure's imaging
procedure
** performed procedure is linked to the scheduled procedure (read-only)
* I am able to
** enter date and time of completion
** enter provider which performed the procedure
** more?

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Simple Case';
1 scheduled procedure step results in 1 performed procedure step

===== PT-6 ADD NON-SCHEDULED PERFORMED PROCEDURE

STORY:: As a performing technician I want to add a performed procedure which was not
scheduled to a requested procedure.

ACCEPTANCE CRITERIA::

* from the requested procedure page I can add a performed procedure
* I can enter all fields of the performed procedure except the link to the
scheduled procedure

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Append Case';
1 scheduled procedure step results in 2 performed procedure step

===== PT-7 CREATE NON-REQUESTED PERFORMED PROCEDURE

STORY:: As a performing technician I want to create a performed procedure which was not requested.

ACCEPTANCE CRITERIA::

* I create a new requested procedure on the requested procedure form and add a
performed procedure to it as in PT-6 where no scheduled procedure exists.  

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Uncheduled Case';
0 scheduled procedure step results in 1 performed procedure step

==== Radiologist - RA

===== RA-1 LIST REQUESTED PROCEDURES

STORY:: As a radiologist I want to see a list of requested procedures which are
completed and thus need reporting.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** performed date
** modality type
** performed procedure code
** status; not yet reported; already reported

