== Requirements

:ihe-tf-rad-title: IHE Radiology Technical Framework
:ihe-tf-rad-url: http://www.ihe.net/Technical_Frameworks/#radiology

This documents shall serve as a requirement for ongoing development and a
documentation of how things are implemented by the {project-short-name}.

The {project-short-name} aims to adhere to best practices defined by the
{ihe-tf-rad-url}[{ihe-tf-rad-title}].

The {project-short-name} shall partially implement the following integration profiles:

* Radiology Scheduled Workflow (SWF)

NOTE: the word partially is used above since {project-short-name} will not
perform all transactions required by the {ihe-tf-rad-title}.

The {project-short-name} acts as the following actors:

* Order Placer (OP)
* Department System Scheduler/Order Filler (DSS/OF)

NOTE: the module does not provide DICOM Modality Worklist services as
attributed to actor 'Department System Scheduler/Order Filler' by IHE, this
service has to be provided by an external system (like a PACS, as for example
done by dcm4chee).

The {project-short-name} implements or acts in the following transactions:

* RAD-2 Placer Order Management
* RAD-3 Filler Order Management
* RAD-4 Procedure Scheduled
* RAD-13 Procedure Update

NOTE: since the {project-short-name} acts as 'Order Placer' and 'Department
System Scheduler/Order Filler' transaction 'RAD-2' and 'RAD-3' are basically merged.
There is no need for the 'DSS/OF' to update/notify the 'OP' on creation, revision,
cancellation of orders, since these actions will always originate at the 'OP'.

=== Background

The following explains the meaning of terms used in this document

* requested procedure: a unit of work which results in a report
* scheduled procedure: smallest unit of work which is scheduled and performed
* performed procedure: smallest unit of work that has actually been performed
which will result in images

=== User Roles

The following describes the user roles interacting with the {project-short-name}.

==== Referring Physician - RP

Doctor ordering a radiological test to be done on a patient.

==== Scheduler - S

Provider who schedules (sets date, time and location/modality) requested imaging procedures.

==== Performing Technician - PT

Technologist performing the imaging procedures on the
patient. To get the scheduled procedures (his TODO list) he has to perform he
can either find it in the {project-short-name} or at the modality through querying
the DICOM Modality Worklist from the PACS.

==== Radiologist - R

Radiologist creates radiological reports for completed requested
procedures.

=== User stories

==== Referring Physician - RP

RP-1:: As a referring physician I want to enter a new radiology order.

Acceptance criteria:

* select patient
* select orderable from concept
* select urgency
* select date and time if order should be scheduled for specific date
* select orderer from providers (in case I am not an RP, but a data clerk with
RP permissions entering the order for an RP)
* enter order reason as free text or from concept (Order.orderReasonNonCoded/orderReason)
* enter a comment for the fulfiller of the order (Order.commentToFulfiller)

NOTE: creating a radiology order does not create a requested procedure, this
transaction represents the 'Order Placer' sending an order request to the
'Department System Scheduler/Order Filler' in terms of IHE actors. In other
terms, any department allowed to create radiology orders sends a request for a
radiology order to the radiology department, but does not interfere with the
exact details of how the order is going to be executed/reported/billed. These
details are a matter of the radiology department.

RP-2:: As a referring physician I want to discontinue an existing radiology order.

Acceptance criteria:

* a radiology order can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A radiology order can be discontinued even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued.

RP-3:: As a referring physician I want to revise an existing radiology order.

Acceptance criteria:

* a radiology order can only be revised as long as no imaging procedure
has been performed.

NOTE: A radiology order can be revised even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued. The radiology department will need to request
and schedule the revised order as if it was a new order.

RP-4:: As a referring physician I want to see a list of radiology orders where
I can narrow down the results by filtering and navigate to a specific radiology
order's or its requested procedure page.

Acceptance criteria:

* filter by patient name or id
* filter by order date
* filter/see if the order has been requested by the radiology department
(does it have a requested procedure?)
* navigate to the radiology order form by selecting a hyperlink in a specific
radiology order's row (for revision/discontinuation of the order)
* navigate to the radiology order's requested procedure (if existing) by
selecting a hyperlink in a specific radiology order's row (to see details about
the requested procedure: scheduled procedures, performed procedures, radiology
report, study)

==== Scheduler - S

S-1:: As a scheduler I want to see a list of requested procedures.

Acceptance criteria:

* filter by patient name or id
* filter by order date
* filter by status; already scheduled or not

S-2:: As a scheduler I want to define the scheduled procedures needed for the
requested procedures.

Acceptance criteria:

* TODO

S-3:: As a scheduler I want to define when (date and time) scheduled procedures will be performed.

Acceptance criteria:

* filter by patient name or id
* filter by order date
* filter by status; already scheduled or not

==== Performing Technician - PT

PT-1:: As a performing technician I want to see a list of scheduled procedures.

Acceptance criteria:

* filter by patient name or id
* filter by scheduled date
* filter by modality
* filter by scheduled procedure code
* filter by status; not yet performed; performed

PT-2:: As a performing technician I want to mark a scheduled procedure as
completed.

Acceptance criteria:

* enter date and time of completion
* enter provider which performed the procedure
* more?

NOTE: see IHE Vol 2 for 'MPPS In Progress, Simple Case'; 1 scheduled procedure step results in 1 performed procedure step

PT-3:: As a performing technician I want to create a performed procedure which was not requested.

Acceptance criteria:

* TODO


NOTE: see IHE Vol 2 for 'MPPS In Progress, Uncheduled Case'; 0 scheduled procedure step results in 1 performed procedure step

PT-4:: As a performing technician I want to add a performed procedure which was not
scheduled to a requested procedure.

Acceptance criteria:

* TODO

NOTE: see IHE Vol 2 for 'MPPS In Progress, Append Case'; 1 scheduled procedure step results in 2 performed procedure step

==== Radiologist - R

R-1:: As a radiologist I want to see a list of requested procedures which are
completed and thus need reporting.

Acceptance criteria:

* filter by patient name or id
* filter by performed date
* filter by modality
* filter by performed procedure code
* filter by status; not yet reported; already reported

