== Requirements

:ihe-tf-rad-title: IHE Radiology Technical Framework
:ihe-tf-rad-vol2: IHE Radiology Technical Framework Vol 2
:ihe-tf-rad-url: http://www.ihe.net/Technical_Frameworks/#radiology

This documents shall serve as a requirement for ongoing development and a
documentation of how things are implemented by the {project-short-name}.

The {project-short-name} aims to adhere to best practices defined by the
{ihe-tf-rad-url}[{ihe-tf-rad-title}].

The {project-short-name} shall partially implement the following integration profiles:

* Radiology Scheduled Workflow (SWF)

NOTE: the word partially is used above since {project-short-name} will not
perform all transactions required by the {ihe-tf-rad-title}.

The {project-short-name} acts as the following actors:

* Order Placer (OP)
* Department System Scheduler/Order Filler (DSS/OF)

NOTE: the module does not provide DICOM Modality Worklist services as
attributed to actor 'Department System Scheduler/Order Filler' by IHE, this
service has to be provided by an external system (like a PACS, as for example
done by dcm4chee).

The {project-short-name} implements or acts in the following transactions:

* RAD-2 Placer Order Management
* RAD-3 Filler Order Management
* RAD-4 Procedure Scheduled
* RAD-13 Procedure Update

NOTE: since the {project-short-name} acts as 'Order Placer' and 'Department
System Scheduler/Order Filler' transaction 'RAD-2' and 'RAD-3' are basically merged.
There is no need for the 'DSS/OF' to update/notify the 'OP' on creation, revision,
cancellation of orders, since these actions will always originate at the 'OP'.

=== TERMS

The following explains the meaning of terms used in this document to establish
common ground

==== Radiology Order

DEFINITION::
A radiology order is a radiological test ordered by a referring physician for a
specific patient.

CONTEXT::
The radiology order is sent to the radiology department for execution.

COMPONENTS::
Its main components are

* patient
* urgency
* start date
* orderable (what kind of test should be done? i.e. "CT of the
Abdomen" or "R/O Pulmonary Embolism")
* orderer (referring physician or other doctor requesting the order)

SPECIAL TERMS::

*COMPLETED:* A radiology order is completed once a radiology report has been created by the
radiology department.

==== Requested Procedure

DEFINITION::
A requested procedure is a unit of work which results in a radiology report.

CONTEXT::
The requested procedure follows an incoming radiology order. The radiology
department decides how the radiology order is going to be exectued in terms of
radiological procedures. Each requested procedure will get one radiology
report.

COMPONENTS::
Its main components are

* one corresponding radiology order
* requested procedure (i.e. "CT ABDOMEN WITH IV CONTRAST"; usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook)
* one or more scheduled procedures which drill down the requested procedure
into schedulable/executable steps
* one or more performed procedures
* one radiology study
* one radiology report

SPECIAL TERMS::

*READY FOR REPORTING:* A requested procedure is 'ready for reporting' as soon
as it has one or more performed procedures and only completed scheduled
procedures.

*COMPLETED OR REPORTED:* A requested procedure is 'completed' or 'reported'
once a radiology report has been created.

==== Scheduled Procedure

DEFINITION::
A scheduled procedure is the smallest unit of work which is scheduled and
performed.

CONTEXT::
The radiology department defines how requested procedures are split up into
units of work. Scheduled procedures are there to reserve resources (imaging
modality, performing technicians, ...) and reflect the steps needed to actually
do the work requested in the requested procedure. As an example if a requested
procedures involves several imaging modalities than these resources need to be
scheduled (reserved) and thus split up into several scheduled procedures.

COMPONENTS::
Its main components are

* corresponding requested procedure
* scheduled procedure (i.e. "CT ABDOMEN WITH IV CONTRAST" usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook)
* modality type (CT, MR, US, ...)
* modality (CT01, MR01, ...)
* scheduled start date
* scheduled start time
* corresponding performed procedure

SPECIAL TERMS::

*SCHEDULED:* A scheduled procedure is 'scheduled' as soon as its 'scheduled
start time', 'scheduled start date' and 'modality' are set.

*COMPLETED OR PERFORMED:* A scheduled procedure is 'completed' or 'performed'
once it has a corresponding performed procedure.

==== Performed Procedure

DEFINITION::
Is the smallest unit of work that has actually been performed which will result
in radiological images.

CONTEXT::
A performed procedure is the actual work done at an imaging modality resulting
in radiological images.

COMPONENTS::
Its main components are

* corresponding requested procedure
* corresponding scheduled procedure (optional, since it happens that
procedures are done without being scheduled first)
* performed procedure (i.e. "CT ABDOMEN WITH IV CONTRAST" usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook. can defer
from the scheduled procedure)
* performed start date
* performed start time
* performing physician

==== Radiology Study

DEFINITION::
The imaging study which holds actual radiological images.

CONTEXT::
TODO

COMPONENTS::
TODO

==== Radiology Report

DEFINITION::
The radiology report is made by a radiologist which documents all
findings made by reading the study's images.

CONTEXT::
TODO

COMPONENTS::
TODO

=== User Roles

The following describes the user roles interacting with the {project-short-name}.

==== Administrator - AD

Administrator of the {project-short-name} configures orderables, DICOM UID org
root used for DICOM Study Instance UID generation, DICOM web viewer details and
other OpenMRS related settings.

==== Referring Physician - RP

Doctor ordering a radiological test to be done on a patient.

==== Scheduler - SC

Provider who schedules (sets date, time and location/modality) requested imaging procedures.

==== Performing Technician - PT

Technologist performing the imaging procedures on the
patient. To get the scheduled procedures (his TODO list) he has to perform he
can either find it in the {project-short-name} or at the modality through querying
the DICOM Modality Worklist from the PACS.

==== Radiologist - RA

Radiologist creates radiological reports for completed requested
procedures.

=== User stories

The following user stories define the interactions of the users with the
{project-short-name}.

User stories are defined in following scheme:
"As a <user role/> I <want/can/need> <action> so that <achievement/goal>."

TIP: read about user stories in 'Mike Cohn -  User Stories Applied'

==== Referring Physician - RP

===== RP-1 CREATE ORDER

STORY:: As a referring physician I want to create a new radiology order.

ACCEPTANCE CRITERIA::

On the radiology order form

* I can
** select patient [required]
** an orderable from concept (i.e. "R/O pulmonary embolism") [required]
** select urgency [required; defaults to ROUTINE]
** select date and time [only required if order urgency is set to ON SCHEDULED DATE]
** select orderer from providers (in case I am not an RP, but a data clerk with
RP permissions entering the order for an RP) [required]
** enter order reason as free text [optional]
** select order reason from concept [optional]
** enter a comment for the fulfiller of the order [optional]

NOTE: creating a radiology order does not create a requested procedure, this
transaction represents the 'Order Placer' sending an order request to the
'Department System Scheduler/Order Filler' in terms of IHE actors. In other
terms, any department allowed to create radiology orders sends a request for a
radiology order to the radiology department, but does not interfere with the
exact details of how the order is going to be executed/reported/billed. These
details are a matter of the radiology department.

===== RP-2 DISCONTINUE ORDER

STORY:: As a referring physician I want to discontinue an existing radiology order.

ACCEPTANCE CRITERIA::

On the radiology order's form

* I can enter
** discontinuation reason (i.e. incorrect orderable ordered, patient refused to
continue treatment, ...) [required]
** provider who ordered the discontinuation [required]
* CONDITION: a radiology order can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A radiology order can be discontinued even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued.

===== RP-3 REVISE ORDER

STORY:: As a referring physician I want to revise an existing radiology order.

ACCEPTANCE CRITERIA::

On the radiology order's form

* I can enter
** TODO
** TODO
* CONDITION: a radiology order can only be revised as long as no imaging procedure
has been performed.

NOTE: A radiology order can be revised even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued since they might no longer match the orderable.
The radiology department will need to create a new requested procedure with its
scheduled procedures for the revised order as if it was a new order.

===== RP-4 LIST ORDERS

STORY:: As a referring physician I want to see a list of radiology orders where
I can narrow down the results by filtering and navigate to a specific radiology
order's or its requested procedure's form.

ACCEPTANCE CRITERIA::

On the radiology order list form

* I can see following columns in the list
** radiology order id (hyperlink to radiology order form)
** patient id + full name (hyperlink to patient dashboard form)
** radiology order orderable
** radiology order urgency
** radiology order start date
** corresponding requested procedure id (hyperlink to requested procedure form)
* I can filter the list by
** patient name or id
** radiology order start date
** filter/see if the order has been requested by the radiology department
(does it have a corresponding requested procedure?)

==== Scheduler - SC

===== SC-1 LIST SCHEDULED PROCEDURES

STORY:: As a scheduler I want to see a list of scheduled procedures where
I can narrow down the results by filtering and navigate to a specific scheduled
procedure's form.

ACCEPTANCE CRITERIA::

On the scheduled procedure list form

* I can see following columns in the list
** scheduled procedure id (hyperlink to the scheduled procedure form)
** corresponding requested procedure id (hyperlink to the requested procedure
form)
** scheduled procedure start datetime
** scheduled procedure's imaging procedure
** scheduled procedure's modality type
** corresponding performed procedure id (hyperlink to the performed procedure
form)
* I can filter the list by
** patient name or id
** scheduled procedure start datetime
** scheduled procedure's imaging procedure
** scheduled procedure's modality type
** scheduled status; already scheduled or not
** performed status; already performed or not

===== SC-2 SCHEDULE SCHEDULED PROCEDURES

STORY:: As a scheduler I want to schedule an existing scheduled procedure.

ACCEPTANCE CRITERIA::

On the scheduled procedure's form

* If the corresponding requested procedure has a radiology order,
a header summarizing the radiology order information should be
shown. The radiology order header shows
** patient
** order number
** accession number
** order orderable
** order urgency
** orderer
** order start date
* I can see a header with the requested procedure information of the scheduled
procedure's corresponding requested procedure. The requested procedure header shows
** requested procedure id
** requested procedure
* I can set the scheduled procedure's start datetime and save it

NOTE: a scheduled procedure can only be scheduled if
* it does not have a corresponding performed procedure i.e. it has not been performed.
* it has not already been scheduled ???

===== SC-3 DISCONTINUE SCHEDULED PROCEDURE

STORY:: As a scheduler I want to discontinue an existing scheduled procedure.

ACCEPTANCE CRITERIA::

On the scheduled procedure's form

* I can enter
** discontinuation reason (i.e. equipment maintenance, patient did not arrive) [required]
** provider who ordered the discontinuation [required]

NOTE: a scheduled procedure can only be discontinued as long as it does
not have a corresponding performed procedure i.e. it has not been performed.

==== Performing Technician - PT

===== PT-1 CREATE REQUESTED PROCEDURE

STORY:: As a performing technician I want to create a requested procedure for a
radiology order.

ACCEPTANCE CRITERIA::

* see a header with the radiology order information of the order I am creating
a requested procedure for (accession number, orderable, orderer, urgency, date
and time, patient)
* select requested procedure from concept (i.e. X-RAY, CHEST)
* QUESTION select a provider which requests this requested procedure (in case I am not a
PT, but a data clerk with PT permissions entering the requested procedure for a PT)
* when I save the requested procedure a study is also created with a Study
Instance UID

IMPORTANT: this story needs clarification. I chose this step to be done by the PT but
it could of course be done by someone else. The step could be automated in case
we have a mechanism in place that maps all orderables to requested procedures
as described by {ihe-tf-rad-title} in 3.4.2 Scheduled Workflow Concepts in
Practice see example of "R/O Pulmonary Embolism". The mapping would then be
configured by each implemenation.

NOTE: the use of the requested procedure is to be able refine how the orderable
is mapped to an imaging procedure. a different kind of code could be used for
orderables and requested procedures. the orderable is closer to what should be
done in an abstract sense and the requested procedure closer to the imaging
procedure.

===== PT-2 DISCONTINUE REQUESTED PROCEDURE

STORY:: As a performing technician I want to discontinue an existing requested
procedure.

ACCEPTANCE CRITERIA::

* a requested procedure can only be discontinued as long as no imaging procedure
has been performed.

NOTE: A requested procedure can be discontinued even if it already has scheduled
procedures, but only as long as there is no performed procedure. The existing requested
procedure and its scheduled procedures will be discontinued.

===== PT-3 ADD SCHEDULED PROCEDURES

STORY:: As a performing technician I want to create and add scheduled procedures to a
requested procedure.

ACCEPTANCE CRITERIA::

* I can see a header with the requested procedure I am adding scheduled
procedures to. The header shows
** radiology order (if exists)
** requested procedure concept
* I can see existing scheduled procedures
* I can add a new scheduled procedure
** select an imaging procedure from concepts 
** select a modality type (CT, MR, US, ... see DICOM standard part 3
C.7.3.1.1.1)

NOTE: again this step could be done by another role, or if a mechanism for
mapping requested procedures to scheduled procedures exists it could be
automated or at least pre-filled for the PT which accepts it (but that would be
another story)

===== PT-4 LIST REQUESTED PROCEDURES

STORY:: As a performing technician I want to see a list of requested procedures
where I can narrow down the results by filtering and navigate to a specific
requested procedure's form.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** requested procedure code
** status; not yet performed; performed (has performed procedures?)
* I can navigate to the requested procedure's form by
selecting a hyperlink in a specific requested procedure's row

===== PT-5 MARK SCHEDULED PROCEDURE AS COMPLETE

STORY:: As a performing technician I want to mark a scheduled procedure as
completed.

ACCEPTANCE CRITERIA::

* when I select the scheduled procedure to complete it I am redirected to the
performed procedure form with all info from the scheduled procedure pre-filled
in the performed procedure's fields
** scheduled procedure start datetime as performed procedure start datetime
** scheduled procedure imaging procedure as performed procedure's imaging
procedure
** performed procedure is linked to the scheduled procedure (read-only)
* I am able to
** enter date and time of completion
** enter provider which performed the procedure
** more?

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Simple Case';
1 scheduled procedure step results in 1 performed procedure step

===== PT-6 ADD NON-SCHEDULED PERFORMED PROCEDURE

STORY:: As a performing technician I want to add a performed procedure which was not
scheduled to a requested procedure.

ACCEPTANCE CRITERIA::

* from the requested procedure form I can add a performed procedure
* I can enter all fields of the performed procedure except the link to the
scheduled procedure

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Append Case';
1 scheduled procedure step results in 2 performed procedure step

===== PT-7 CREATE NON-REQUESTED PERFORMED PROCEDURE

STORY:: As a performing technician I want to create a performed procedure which was not requested.

ACCEPTANCE CRITERIA::

On the requested procedure form

* I create a new requested procedure on the requested procedure form and add a
performed procedure to it as in PT-6 where no scheduled procedure exists.  

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Uncheduled Case';
0 scheduled procedure step results in 1 performed procedure step

==== Radiologist - RA

===== RA-1 LIST REQUESTED PROCEDURES

STORY:: As a radiologist I want to see a list of requested procedures which are
completed and thus need reporting.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** performed date
** modality type
** performed procedure code
** status; not yet reported; already reported

