== Requirements

:ihe-tf-rad-title: IHE Radiology Technical Framework
:ihe-tf-rad-vol2: IHE Radiology Technical Framework Vol 2
:ihe-tf-rad-url: http://www.ihe.net/Technical_Frameworks/#radiology

This documents shall serve as a requirement for ongoing development and a
documentation of how things are implemented by the {project-short-name}.

The {project-short-name} aims to adhere to best practices defined by the
{ihe-tf-rad-url}[{ihe-tf-rad-title}].

The {project-short-name} shall partially implement the following integration profiles:

* Radiology Scheduled Workflow (SWF)

NOTE: the word partially is used above since {project-short-name} will not
perform all transactions required by the {ihe-tf-rad-title}.

The {project-short-name} acts as the following actors:

* Order Placer (OP)
* Department System Scheduler/Order Filler (DSS/OF)

NOTE: the module does not provide DICOM Modality Worklist services as
attributed to actor 'Department System Scheduler/Order Filler' by IHE, this
service has to be provided by an external system (like a PACS, as for example
done by dcm4chee).

The {project-short-name} implements or acts in the following transactions:

* RAD-2 Placer Order Management
* RAD-3 Filler Order Management
* RAD-4 Procedure Scheduled
* RAD-13 Procedure Update

NOTE: since the {project-short-name} acts as 'Order Placer' and 'Department
System Scheduler/Order Filler' transaction 'RAD-2' and 'RAD-3' are basically merged.
There is no need for the 'DSS/OF' to update/notify the 'OP' on creation, revision,
cancellation of orders, since these actions will always originate at the 'OP'.

### Judy

I like to think of the radiology functionality around three main users

1. Ordering clinicians - These guys need to order tests , and view results <br>
2. Radiologists - Care about reading studies...They may need to look up patient histories
- there are two levels of radiologists : Residents and Consultants. The residents dictate the first report called a preliminary report , that when read by the radiologist is approved as the final reports. Therefore there are multiple states of the report including Draft, Preliminary , and Final reports.
3. The technicians - these guys are in charge of getting the test done. Once an order is created they get a modality worklist that is used to do the procedures and then once the correct images are available , the study is saved and pushed to PACS.
Once the study is completed then the radiologist can dictate the study. If there is an error eg date or study cancellation , most of this is done by technologists
4. Admin - this is usually the lady sitting at the front office when you come to radiology. They want to check are you scheduled for any study and is the date correct and check in to show you are available
5. Admin technical who corrects reports etc

=== Terms

The following explains the meaning of terms used in this document to establish
common ground

==== Radiology Order

DEFINITION::
A radiology order is a radiological test ordered by a referring physician for a
specific patient.

CONTEXT::
The radiology order is sent to the radiology department for execution.


###Judy::

```
There is a use case where an outside image(done from a different facility is obtained and brought by the patient
and needs to be read at the local facility).Therefore there is an order for "Outside Interpretation" which would include
1. Patient Name (First , Middle and Last Name)/ MRN
2. Study type eg CT head
3. Name of facility
4. Whether report is available..

This would create a new study that is complete (after images are uploaded to the PACS system) and a user can claim a report. The label for this study would be
OUTSIDE CT HEAD .. etc
```

COMPONENTS::
Its main components are

* patient details (MRN/Name)
* urgency (These are priorities. Some people use numbers eg 0 for must be read immediately, 2 for ED studies , 4 for inpatients and 5 for outpatient /non emergent studies). These could be set up as a global property that can be changed by the person creating
the order , and this field created as a drop down.
* start date -- I would change this to Study Date...
* orderable (what kind of test should be done? i.e. "CT of the
Abdomen" or ~~"R/O Pulmonary Embolism"~~) The R/O Pulmonary Embolism is an order reason
- This orderable should be a convenient set . In the concept dictionary provided by CIEL , there is a concept class of Radiology/Imaging Procedure. By default the module should pull up the concepts with class in the orderable section.
However using a global property then an institution can create a convenient set that can be used to populate the orderables.
* orderer (referring physician or other doctor requesting the order)
* order reason free text or from a standardized code scheme - I would label this as Reason for Study. I think we should have two fields where the first one is a standard schema in the dictionary would be  any concept with class of diagnosis
and a second field with Additional History which is free text.
~~* corresponding requested procedure (created by the radiology department)~~  Not clear how we would use this ..I would remove it

###Additional Notes:
1. Decide on Mandatory fields from above - patient details , Priority (instead of Urgency), Date, Test, Orderer and Diagnosis
2. Wishlist - in future work to incorporate a decision support tool like ACR appropriateness criteria to help ordering doctors figure out the best test for them :: See http://www.acr.org/quality-safety/appropriateness-criteria/acr-select and http://www.acr.org/~/media/ACR/Documents/AppCriteria/Misc/ACRSelect_CPOE.pdf

SPECIAL TERMS::

*SCHEDULED:* A radiology order is 'scheduled' if its corresponding requested
procedure is 'scheduled'.

*IN PROGRESS:* A radiology order is 'in progress' if its corresponding requested
procedure is 'in progress'.

*READY FOR REPORTING:* A radiology order is 'ready for reporting' if its
corresponding requested procedure is 'ready for reporting'.

*COMPLETED:* A radiology order is 'completed' if its corresponding requested
procedure is 'completed'.

==== Requested Procedure  ### I dont know if we need to implement anything here .. I would delete this ..

DEFINITION::
A requested procedure is a unit of work which results in a radiology report.

CONTEXT::
The requested procedure follows an incoming radiology order. The radiology
department decides how the radiology order is going to be exectued in terms of
radiological procedures. Each requested procedure will get one radiology
report.

COMPONENTS::
Its main components are

* one corresponding radiology order
* requested procedure (i.e. "CT ABDOMEN WITH IV CONTRAST"; usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook)
* one or more scheduled procedures which drill down the requested procedure
into schedulable/executable steps
* one or more performed procedures
* one radiology study
* one radiology report

~~SPECIAL TERMS::~~
~~*SCHEDULED:* A requested procedure is 'scheduled' if all of its
scheduled procedures are 'scheduled'.~~

~~*IN PROGRESS:* A requested procedure is 'in progress' if it has at least one
performed procedure.~~

~~*READY FOR REPORTING:* A requested procedure is 'ready for reporting' if all of
its scheduled procedures are 'completed'; if it has at least one 'completed'
scheduled procedure and the other scheduled procedures are 'discontinued' or it has
only 'discontinued' scheduled procedures and at least one performed procedure.~~

~~*COMPLETED:* A requested procedure is 'completed' once a radiology report has
been created.~~

==== Scheduled Procedure

DEFINITION::
A scheduled procedure is the smallest unit of work which is scheduled and
performed.

CONTEXT::
The radiology department defines how requested procedures are split up into
units of work. Scheduled procedures are there to reserve resources (imaging
modality, performing technicians, ...) and reflect the steps needed to actually
do the work requested in the requested procedure. As an example if a requested
procedures involves several imaging modalities than these resources need to be
scheduled (reserved) and thus split up into several scheduled procedures.

COMPONENTS::
Its main components are

* corresponding requested procedure
* scheduled procedure (i.e. "CT ABDOMEN WITH IV CONTRAST" usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook)
* modality type (CT, MR, US, ...)
* modality (CT01, MR01, ...)
* scheduled start date
* scheduled start time
* corresponding performed procedure

SPECIAL TERMS::

*SCHEDULED:* A scheduled procedure is 'scheduled' as soon as its 'scheduled
start time', 'scheduled start date' and 'modality' are set.

*COMPLETED:* A scheduled procedure is 'completed' once it has a corresponding
performed procedure.

==== Performed Procedure

DEFINITION::
Is the smallest unit of work that has actually been performed which will result
in radiological images.

CONTEXT::
A performed procedure is the actual work done at an imaging modality resulting
in radiological images.

COMPONENTS::
Its main components are

* corresponding requested procedure
* corresponding scheduled procedure (optional, since it happens that
procedures are done without being scheduled first)
* performed procedure (i.e. "CT ABDOMEN WITH IV CONTRAST" usually coming
from a standardized code scheme such as SNOMED CT or RadLex Playbook. can defer
from the scheduled procedure)
* performed start date
* performed start time
* performing physician

### I guess the above is good for definitions but i dont think it helps us be specific in our functionality . This is good information for reference or reading

==== Radiology Study

DEFINITION::
The radiology study holds actual radiological images.

CONTEXT::
The radiology study represents what is called study by the DICOM standard.
The use of a radiology study in the {project-short-name} is to generate a Study
Instance UID which will propagate vie the DICOM Modality Worklist provided by
the PACS to the imaging modality. The imaging modality will put the Study
Instance UID in the images it creates. This allows the {project-short-name} to
access the DICOM study and its images in the PACS via the Study Instance UID.


### Judy : Remember we have a Study , then series and then instance... so a CT Head is a study , then it can be axial , coronal or sagittal (the series) and each image in the series is an instance
- Summarizing the above i think of the following functionality
1. Ability to schedule an exam (this is in the orderable data where the date of examination is selected)
2. Ability to create a modality worklist that can be queried by day
3. Ability to cancel the examination -- if the patient cannot pay or dies -- and it gets the status cancelled
4. Generate an accession ID (or a study ID that we can track for reporting)
5. Support performance of a study by the technologist and set the status to completed both in RIS and using the MPPS .


COMPONENTS::
Its main components are

* study ID
* study instance UID (unique identifier of the study)

==== Radiology Report

DEFINITION::
The radiology report is made by a radiologist which documents all
findings made by reading the study's images.

CONTEXT::
Once a requested procedure is 'ready for reporting' a radiologist can claim the
requested procedure for reporting and create the report.

COMPONENTS::
Its main components are

* Radiology study / procedure
* report status (claimed, ~~completed, discontinued~~) - preliminary , draft or finalized
* report date
* radiologist writing the report
* report text

```
### Judy : Need a way to add an addendum to a report (if a mistake was made , or we have new images with new findings)
The report requirements are described in detail in this document :::  https://docs.google.com/document/d/17u8kwEk-2D47ZsfSy_WM5LdpIuXwPm9LAQuoOSbQHHA/edit?usp=sharing

in summary
1. A radiologist should see a reading list
2. They should pick a study from the list
3. They can type a report
4. They can edit a report
5. They can create an addendum in a  finalised report
6. They can use templates
    a) We need a report management system that allows the radiologists to create new templates, edit templates and delete templates
    b) Share templates with each other/ across multiple systems

Wishlist:
1. Create multimedia reports that reference images within a radiology report.
```

SPECIAL TERMS::

*CLAIMED:* A radiology report is 'claimed' if a radiologist has claimed to
work on a requested procedure that is 'ready for reporting'.

*COMPLETED:* A radiology report is 'completed' once a radiologist has set the
reports status to 'completed'.

=== User Roles

### Judy : These roles specify the view of the dashboard that the user sees.. eg a radiologist wants to go to the reading list, while a technologist wants to see the
modality work list. The ordering doctor should see a list of studies for the patients that are pending , completed and be able to view the report

The following describes the user roles interacting with the {project-short-name}.

==== Administrator - AD

Administrator of the {project-short-name} configures orderables, DICOM UID org
root used for DICOM Study Instance UID generation, DICOM web viewer details and
other OpenMRS related settings.

==== Referring Physician - RP

Doctor ordering a radiological test to be done on a patient.

==== Scheduler - SC

Provider who schedules (sets date, time and location/modality) requested imaging procedures.

==== Performing Technician - PT

Technologist performing the imaging procedures on the
patient. To get the scheduled procedures (his/her TODO list) he has to perform he
can either find it in the {project-short-name} or at the modality through querying
the DICOM Modality Worklist from the PACS.

==== Radiologist - RA

Radiologist creates radiological reports for completed requested
procedures.

=== User stories

The following user stories define the interactions of the users with the
{project-short-name}.

User stories are defined in following scheme:
"As a <user role/> I <want/can/need> <action> so that <achievement/goal>."

TIP: read about user stories in 'Mike Cohn -  User Stories Applied'

==== Referring Physician - RP

===== CREATE ORDER

STORY::
As a referring physician I want to create a radiology order.

ACCEPTANCE CRITERIA::

* Verify that a referring physician can enter a new radiology order by entering
** patient
** an orderable from concepts eg CT head with contrast ~~(i.e. "R/O pulmonary embolism")~~
** urgency [choose from EMERGENCY, ROUTINE, ON SCHEDULED DATE;
defaults to ROUTINE]
** date and time
** orderer from providers (in case I am not an RP, but a data clerk with
RP permissions entering the order for an RP)
** order reason as free text
** order reason from concept eg ICD 9 diagnosis code
** a comment for the fulfiller of the order
* Verify that a referring physician needs to enter a patient, orderable,
urgency and orderer
* Verify that a referring physician only needs to enter an order date and time
if urgency is set to ON SCHEDULED DATE
* ~~Verify that a non-referring physician cannot create a radiology order~~  ### Judy : Not sure about this .. do you have a specific example?

NOTE: creating a radiology order does not create a requested procedure, this
transaction represents the 'Order Placer' sending an order request to the
'Department System Scheduler/Order Filler' in terms of IHE actors. In other
terms, any department allowed to create radiology orders sends a request for a
radiology order to the radiology department, but does not interfere with the
exact details of how the order is going to be executed/reported/billed. These
details are a matter of the radiology department.

### Judy : not sure of above sentence

===== DISCONTINUE ORDER

STORY:: As a referring physician I want to discontinue a radiology order.

ACCEPTANCE CRITERIA::

* Verify that a referring physician can discontinue a radiology order by
entering
** discontinuation reason (i.e. incorrect orderable ordered, patient refused to
continue treatment, ...)
** provider who ordered the discontinuation
* Verify that a referring physician needs to enter discontinuation reason and
provider
* Verify that a non-referring physician cannot discontinue a radiology order
* Verify that a referring physician cannot discontinue the radiology order if
it is 'in progress', 'ready for reporting' or 'completed'.

NOTE: A radiology order can be discontinued even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued.

===== LIST ORDERS

STORY:: As a referring physician I want to see a list of radiology orders so
that I can navigate to a specific radiology order's order form or its patient
dashboard form or its corresponding requested procedure's form.

ACCEPTANCE CRITERIA::

* Verify that a referring physician can see a list of radiology orders with
following columns
** radiology order id
** patient id + full name (hyperlink to patient dashboard form)
** radiology order orderable
** radiology order urgency
** radiology order start date
* Verify that a referring physician can navigate to a radiology order's form
via its radiology order id value
* Verify that a referring physician can navigate to a patient's dashboard form
via its patient id + full name value
* Verify that a referring physician can filter the list by
** patient name or id
** radiology order start date

===== REVISE ORDER

STORY:: As a referring physician I want to revise an existing radiology order.

ACCEPTANCE CRITERIA::

* Verify that a referring physician can revise a radiology order by
** TODO
* Verify that a non-referring physician cannot revise a radiology order
* Verify that a referring physician cannot revise the radiology order if
it is 'in progress', 'ready for reporting' or 'completed'.

NOTE: A radiology order can be revised even if it already has a
requested procedure with scheduled procedures, but only as long as there is no
performed procedure. The existing requested procedure and its scheduled
procedures will be discontinued since they might no longer match the orderable.
The radiology department will need to create a new requested procedure with its
scheduled procedures for the revised order as if it was a new order.

===== FILTER ORDER LIST BY STATUS

STORY:: As a referring physician I want to filter the list of radiology orders
by its status so I can get only orders that are 'in progress', 'ready for
reporting', 'completed'.

ACCEPTANCE CRITERIA::

* TODO

==== Scheduler - SC

===== LIST SCHEDULED PROCEDURES

STORY:: As a scheduler I want to see a list of scheduled procedures so that I
can see what procedures have been and what procedures still need to be
scheduled.

ACCEPTANCE CRITERIA::

* Verify that a scheduler can see a list of scheduled procedures with following
columns
** scheduled procedure id
** scheduled procedure start datetime
** scheduled procedure's imaging procedure
** scheduled procedure's modality type
** corresponding performed procedure id
* Verify that a scheduler can filter the list by
** patient name or id
** scheduled procedure start datetime
** scheduled status; already scheduled or not
* Verify that a scheduler can navigate to a scheduled procedure's form
via its scheduled procedure id value

===== SCHEDULE SCHEDULED PROCEDURES

STORY:: As a scheduler I want to schedule an existing scheduled procedure so
that it can be performed by a performing technician.

ACCEPTANCE CRITERIA::

* Verify that a scheduler can schedule a scheduled procedure by setting its
scheduled procedure start datetime
* Verify that a scheduler can see a header with radiology order information if
the corresponding requested procedure has a radiology order. The radiology
order header should show
** patient
** order number
** accession number
** order orderable
** order urgency
** orderer
** order start date
* Verify that a scheduler can only schedule a scheduled procedure if it is
not 'scheduled' or 'completed'

===== DISCONTINUE SCHEDULED PROCEDURE

STORY:: As a scheduler I want to discontinue a scheduled procedure.

ACCEPTANCE CRITERIA::

* Verify that a scheduler can discontinue a scheduled procedure by entering
** discontinuation reason (i.e. equipment maintenance, patient did not arrive)
** provider who ordered the discontinuation
* Verify that a scheduler needs to enter discontinuation reason and
provider to discontinue a scheduled procedure
* Verify that a non-scheduler cannot discontinue a scheduled procedure
* Verify that a scheduler can discontinue the scheduled procedure if
it is 'scheduled'
* Verify that a scheduler cannot discontinue the scheduled procedure if
it is 'completed'

### Judy: Just remember to create this as a role for scheduling since the PT can work as a ascheduler too

==== Performing Technician - PT

===== CREATE REQUESTED PROCEDURE

STORY:: As a performing technician I want to create a requested procedure with
scheduled procedures for a radiology order so that it can be scheduled by the
scheduler.

ACCEPTANCE CRITERIA::

* Verify that a performing technician can create a requested procedure by
entering
** a requested procedure from a concept (i.e. X-RAY, CHEST)
** adding one or more scheduled procedures (with imaging procedure from concepts,
modality type (CT, MR, US, ...)
* Verify that the performing technician sees a a summary with radiology order
information of the radiology order he is creating the requested procedure for.
The summary should show
** accession number
** orderable
* Verify that the performing technician has to add at least one scheduled
procedure
* Verify that when a requested procedure is created a radiology study with a
Study Instance UID is is created as well
* Verify that a non-performing technician cannot create a requested procedure

IMPORTANT: this story needs clarification. I chose this step to be done by the PT but
it could of course be done by someone else. The step could be automated in case
we have a mechanism in place that maps all orderables to requested procedures
as described by {ihe-tf-rad-title} in 3.4.2 Scheduled Workflow Concepts in
Practice see example of "R/O Pulmonary Embolism". The mapping would then be
configured by each implemenation.

###Judy : I am not sure the exact question. I think the PT should be seeing a modality worklist , select a study , and once its complete  update the status of the study
The PT should be able to change some values on the modality worklist eg if contrast is given or not. Also there should be a place for Technologist Notes that should be dsiplayed to the
radiologist. Eg if patient was not cooperative for a study

NOTE: the use of the requested procedure is to be able refine how the orderable
is mapped to an imaging procedure. a different kind of code could be used for
orderables and requested procedures. the orderable is closer to what should be
done in an abstract sense and the requested procedure closer to the imaging
procedure.

===== DISCONTINUE REQUESTED PROCEDURE

STORY:: As a performing technician I want to discontinue a requested
procedure so that it will not be performed.

ACCEPTANCE CRITERIA::

* Verify that a performing technician can discontinue a requested procedure by
entering
** discontinuation reason (i.e. equipment maintenance, ...)
** provider who ordered the discontinuation
* Verify that a performing technician needs to enter discontinuation reason and
provider to discontinue a scheduled procedure
* Verify that a non-performing technician cannot discontinue a requested procedure
* Verify that a performing technician can discontinue the requested procedure if
it is 'scheduled'
* Verify that a performing technician cannot discontinue the requested procedure if
it is 'in progress', 'ready for reporting' or 'completed'
* Verify that when the requested procedure is discontinued its scheduled
procedures are discontinued as well

TODO
----------------
stories are ok until here, need to do more work on the following

### Judy : Remember in terms of performance , there is no difference between an imaging study and a procedure .. A procedure would be like CT biopsy or hysterosalpingogram that all have the same
workflow. Therefore i would merge the section below with the modality worklist

===== LIST REQUESTED PROCEDURES

STORY:: As a performing technician I want to see a list of requested procedures
where I can narrow down the results by filtering and navigate to a specific
requested procedure's form.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** requested procedure code
** status; not yet performed; performed (has performed procedures?)
* I can navigate to the requested procedure's form by
selecting a hyperlink in a specific requested procedure's row

===== MARK SCHEDULED PROCEDURE AS COMPLETE

STORY:: As a performing technician I want to mark a scheduled procedure as
completed.

ACCEPTANCE CRITERIA::

* when I select the scheduled procedure to complete it I am redirected to the
performed procedure form with all info from the scheduled procedure pre-filled
in the performed procedure's fields
** scheduled procedure start datetime as performed procedure start datetime
** scheduled procedure imaging procedure as performed procedure's imaging
procedure
** performed procedure is linked to the scheduled procedure (read-only)
* I am able to
** enter date and time of completion
~~** enter provider which performed the procedure~~
** Want to enter technologist notes for occurrences that may have opened abotu the study

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Simple Case';
1 scheduled procedure step results in 1 performed procedure step

===== ADD NON-SCHEDULED PERFORMED PROCEDURE

STORY:: As a performing technician I want to add a performed procedure which was not
scheduled to a requested procedure.

ACCEPTANCE CRITERIA::

* from the requested procedure form I can add a performed procedure
* I can enter all fields of the performed procedure except the link to the
scheduled procedure

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Append Case';
1 scheduled procedure step results in 2 performed procedure step

===== CREATE NON-REQUESTED PERFORMED PROCEDURE

STORY:: As a performing technician I want to create a performed procedure which was not requested.

ACCEPTANCE CRITERIA::

On the requested procedure form

* I create a new requested procedure on the requested procedure form and add a
performed procedure to it as in the case where no scheduled procedure exists.

NOTE: see {ihe-tf-rad-vol2} for 'MPPS In Progress, Uncheduled Case';
0 scheduled procedure step results in 1 performed procedure step

==== Radiologist - RA

===== LIST REQUESTED PROCEDURES

STORY:: As a radiologist I want to see a list of requested procedures which are
completed and thus need reporting.

ACCEPTANCE CRITERIA::

* I can see following columns in the list
* I can filter the list by
** patient name or id
** performed date
** modality type
** performed procedure code
** status; not yet reported; already reported

### Judy :: I want to claim a report , type it and complete it
- Be able to see my residents reports and edit them before approving them
- Create an addendum to a finalized report
- Notify other providers of a critical message (wishlist)
- manage my templates by creating new ones , editing existing ones and deleting old ones
- Migrate my templates from one system to another 
